### ISSUE TITLE
published 0.4.1 is not correctly builded

### ISSUE THREAD

**Issue by jamuhl** [yonatanmn/react-inline-auto-prefixer#4]
on 0.4.1 published on npm the line https://github.com/KABA-CCEAC/react-inline-auto-prefixer/blob/master/dist/react-inline-auto-prefixer.js#L133 is missing.

so in cases the userAgent does not match we get errors.

please publish a new build based on 0.4.1 containing that.

**Comment by yonatanmn** [comment]
Right! my mistake
now @0.4.2

**Comment by jamuhl** [comment]
perfect...thanks
